name: Build on Push

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - .gitignore
      - .editorconfig

permissions: write-all # 给所有工作写权限


jobs:
  jobs_v:
    name: Pre-Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Output Build Infomation
        run: |
          latest_commit_message=$(git log -1 --pretty=%B)
          echo latest_commit_message

  jobs_window:
    needs: jobs_v # 等待 jobs_v 任务完成才执行
    name: Build Windows Installer
    timeout-minutes: 60
    runs-on: windows-2022
    env:
      version: ${{ needs.jobs_v.outputs.version }}
      body: ${{ needs.jobs_v.outputs.Body }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Creating Cache Folder
        uses: actions/cache@v3
        with:
          path: |
            C:\npm\cache
          key: ${{ runner.os }}-js-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-js-
      - name: Read Env Params
        run: |
          echo ${{ format('version {0}', env.version ) }} # 版本号
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'
          cache-dependency-path: |
            **/go.sum
            **/go.mod
          go-version-file: 'go.mod'
      - run: go version
      - name: Install Wails V2
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails
      - name: Compile Installer
        run: |
          mkdir -p build/installer 
          wails build -webview2 embed -nsis
          cd build/installer
          ls
      - name: Upload Release
        uses: actions/upload-artifact@v3
        with:
          name: Windows Installer
          path: build/installer/Starburst Overlay-installer.exe
          retention-days: 7
